# Generated by Django 3.2.5 on 2021-07-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotteryregistration',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='lotteryregistration',
            name='last_name',
        ),
    ]
