# Generated by Django 3.2.5 on 2021-07-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_api', '0003_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
